### ISSUE TITLE
Support for ALPHA ESS Wallbox

### ISSUE THREAD

**Issue by Rasenkardinal** [CharlesGillanders/homeassistant-alphaESS#105]
Hey there,

I'm using the integration for a while now. I'm planning to install a WallBox for charging an electric car. Now I wonder if the integration supports an ALPHA ESS Wallbox and allows control of charging behavior etc.

Best regards and thanks for your contribution to us!

**Comment by Poshy163** [comment]
Hey there, we currently pull all the data we can from the offical alphaESS openapi. which the full list of what we get is [here](https://open.alphaess.com/developmentManagement/apiList) (you need an openAPI account to see).

You could maybe make an issue [here](https://github.com/alphaess-developer/alphacloud_open_api/issues) and suggest it? not sure how far it will go tho, as the lead dude isn't too cooperative at the best of times
