### ISSUE TITLE
AL500 SN SMILE5 Grid Feed-In

### ISSUE THREAD

**Issue by CadeusTheGreat** [CharlesGillanders/homeassistant-alphaESS#106]
Hello, not sure if there is an API available for this feature yet as I believe for the SMILE5 inverter the feature is new for only AL500 serial numbers. On the web browser you can now force feed-in to the grid and it would be great if we could work on getting this functionality into Home Assistant or ready for a wider rollout by Alpha.

![image](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/66471724/9086a4b6-bdd5-4fd3-bcfc-0cba1ede850b)

**Comment by CharlesGillanders** [comment]
My integration can only support what's in the AlphaESS API.  You should log a request with that project first if you want to see this functionality.

**Comment by CadeusTheGreat** [comment]
Request has been raised by someone else here: https://github.com/alphaess-developer/alphacloud_open_api/issues/64
I will close this issue until if/when Alpha develops the API.

**Comment by matt-oneill** [comment]
still pushing for it, they seem reluctant to add the feature

**Comment by CadeusTheGreat** [comment]
Yeah, I'm not sure what's going on in that request with Alpha. If those sentences are meant to make sense then I need to relearn English. lmao
