### ISSUE TITLE
Calling the Charging Service

### ISSUE THREAD

**Issue by hjpfourie** [CharlesGillanders/homeassistant-alphaESS#107]
Calling the service the first time seems to work, but subsequent calls don't seem to work. Then randomly after a period of time, it seems to work again, but only the first service call. Anyone else experienced this?

**Comment by CharlesGillanders** [comment]
There is a rate limit at AlphaESS - calls to set charge/discharge only permit one call every ten minutes. (I believe that's the current limit, it had been even lower previously).

**Comment by hjpfourie** [comment]
Ok, that would explain it. Rather annoying as I have 2 inverters so can't set one after the other in my automation.
