### ISSUE TITLE
Values are Incorrect

### ISSUE THREAD

**Issue by Buttercream91** [CharlesGillanders/homeassistant-alphaESS#11]
Hey Charles,

Im a day one noob and I am trying to configure Home Assistant to turn off my Aircon when solar production drops below a certain value but the values displayed on the energy tab don't align with my actual generation, consumption or grid feed in.
![Energy Wheel](https://user-images.githubusercontent.com/92200094/147863575-5583df72-7717-4c2f-a5f3-2e00da3743bd.PNG)

![InkedScreenshot_20220102-120551_AlphaESS_LI](https://user-images.githubusercontent.com/92200094/147863613-e703e184-05fd-4d10-9cbe-54cba6c24351.jpg)

And this is how I have set it up in Home Assistant.

![Setup](https://user-images.githubusercontent.com/92200094/147863634-78bfbef6-d70b-47f2-b20b-a1ceca94e582.PNG)

My battery is the Smile BAT 10.1P/10.3P Integrated EMS V03.
Any help would be appreciated, sorry for the formatting.

**Comment by Buttercream91** [comment]
From my logs:
![Capture](https://user-images.githubusercontent.com/92200094/147863850-d799786f-7628-4aa7-af75-f3c8fc674f35.PNG)
![Capture2](https://user-images.githubusercontent.com/92200094/147863851-eb25e739-98c7-4415-ae80-63107116e3ca.PNG)

**Comment by Buttercream91** [comment]
It has occurred to me that these values aren't the instantaneous values, but instead the overall generation, so all working as intended I guess.

**Comment by Spookster** [comment]
Im a noob to Charles work too, and Im impressed so far
One other git to look at, is :
https://github.com/DasLetzteEinhorn/AlphaESS_Monitor_Hass
The data is a little more current via MQTT (every minute) and accesses a few different things such as ppv1/2
You could easily run both to get the most current / useful data

**Comment by Spookster** [comment]
This is some of the basic data it gets.
Some of the values are unused (and not identified yet)
But as far as installing and update speed, works well.
It doesnt integrate into the energy tab like Charles work though, which is why its complementary to have perhaps both integrations

`{
    "_id": "xxxxxxxxxxxxx",
    "createtime": "2022-01-01 22:01:39",
    "uploadtime": "2022-01-02 11:01:14",
    "sn": "ALXXXXXXXXXXX",
    "ppv1": 3045,
    "ppv2": 1194,
    "ppv3": 0,
    "ppv4": 0,
    "preal_l1": 4071,
    "preal_l2": 0,
    "preal_l3": 0,
    "pmeter_l1": -3439,
    "pmeter_l2": 0,
    "pmeter_l3": 0,
    "pmeter_dc": 0,
    "soc": 100,
    "factory_flag": 0,
    "pbat": 0,
    "sva": 4060,
    "varac": -379,
    "vardc": 0,
    "ev1_power": 0,
    "ev1_chgenergy_real": 0,
    "ev1_mode": 0,
    "ev2_power": 0,
    "ev2_chgenergy_real": 0,
    "ev2_mode": 0,
    "ev3_power": 0,
    "ev3_chgenergy_real": 0,
    "ev3_mode": 0,
    "ev4_power": 0,
    "ev4_chgenergy_real": 0,
    "ev4_mode": 0,
    "poc_meter_l1": 0,
    "poc_meter_l2": 0,
    "poc_meter_l3": 0
}`

![Untitled](https://user-images.githubusercontent.com/982535/147888509-11f2d4f7-181e-4637-86bb-feb2eea775ca.png)

**Comment by Memorist23** [comment]
Hey Charles
Would be great if you gave us a guide on the HA setup side.
I’m with the other guys, I seem to be getting g the wrong data as well.

**Comment by CharlesGillanders** [comment]
Today I added additional sensors that read the instantaneous values as well as the cumulative figures for the day.  I believe that should give you the data that you are looking for.
