### ISSUE TITLE
Documentation of values in ha

### ISSUE THREAD

**Issue by Mjimsas** [CharlesGillanders/homeassistant-alphaESS#115]
Hey, this is just a general question but is there any documentation/information regarding the meaning of the values that get exposed in HA?

**Comment by CadeusTheGreat** [comment]
Are you able to elaborate? I could put together a docs page for what all the values mean if that would be helpful. i.e. total load, state of charge, charge, discharge etc... If that's the values you're referring to. :)

**Comment by Mjimsas** [comment]
Yes exactly that. For my use case i found the values i needed. I found that the values exposed in HA (naming) are different from the ones written in the api docs from alphaESS themselves.

**Comment by Mjimsas** [comment]
For my use case i wanted to have the current discharge in W. But didn't know which value to use for this. In the end i think that this sensor value exposed by the integration: 
![image](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/149004029/8f85c34f-881e-4e61-8616-95741f089c09)

Seems to correspond with this one in the alphaESS api docs.
![image](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/149004029/04f4a566-397f-43d4-a83b-fb4bedc3c7d1)

For me it was guess work and a bit of logical thinking to figure out what value was the one i actually needed.

**Comment by CharlesGillanders** [comment]
I'm working on the assumption that Instantaneous Load is the total demand of the house on the inverter.  

That demand could be partly met by the grid, partly met by solar generation and partly met by battery discharge.  

The pload value is indeed what I'm using but we may have different interpretations of what the alpha documentation means....
