### ISSUE TITLE
Modbus Integration

### ISSUE THREAD

**Issue by x4N70pHyLL** [CharlesGillanders/homeassistant-alphaESS#119]
Hello,
can we also have Modbus integration here?

There are several threads in the german Alpha ESS Forum describing how it is integrated in IOBroker and there is specifically a script for polling the Modbus TCP data.

https://www.storion4you.de/thread/816-alpha-ess-und-home-assistant/?pageNo=1

As it has same/similar data points (obviously) it would be logical for me to integrate it here. 

BTW: Any plans to make this integration "official" to Home Assistant Core?

**Comment by CharlesGillanders** [comment]
I don’t have any modbus hardware so there’s no way for me to maintain a modbus integration.  Very happy for anyone else to propose code to pull if you want to maintain it.

The integration is waiting for inclusion in the default HACS repos - that’s where I’m looking at currently for distribution.
