### ISSUE TITLE
Sunshine at night

### ISSUE THREAD

**Issue by KortgatGH** [CharlesGillanders/homeassistant-alphaESS#127]
It may be coincidence, but since the previous update I get this every day:

![image](https://github.com/user-attachments/assets/9f6ca9c7-2bab-431a-a5e9-a8ffdae4ed99)

The irregular energy reports coincide with false dips in solar production:

![image](https://github.com/user-attachments/assets/7ba3f74c-af96-4d34-90de-5665196442d3)

Any advice would be greatly appreciated.

**Comment by Poshy163** [comment]
Can you confirm if these values (the 0) are shown in the logs or not? and see if its coming through the API (aka the information alpha is providing us)?

**Comment by KortgatGH** [comment]
@Poshy163 thanks for taking interest in this.
I see no log entries in the system log that correlate with the times of these zero value anomalies. I also see no indication of any anomaly when looking at the Alpha data on the app or web portal.

**Comment by dhi20** [comment]
I've got the same issue. The debug log shows the following. It seems to be impacting every sensor which records a total kWh value (solar, charge, discharge, grid etc).


Logger: alphaess.alphaess
Source: custom_components/alphaess/coordinator.py:54
integration: Alpha ESS ([documentation](https://github.com/CharlesGillanders/homeassistant-alphaESS), [issues](https://github.com/CharlesGillanders/homeassistant-alphaESS/issues))
First occurred: 12:01:00 AM (82 occurrences)
Last logged: 9:28:29 AM

```
Unexpected json_response : {'code': 6026, 'msg': 'network is busy', 'expMsg': 'nested exception is org.apache.ibatis.exceptions.PersistenceException: \n### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.\n### The error may exist in class path resource [mapper/td/SysColdataMapper.xml]\n### The error may involve com.alphaess.api.mapper.td.SysColdataMapper.selectOneDayLastPowerBysn\n### The error occurred while executing a query\n### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.', 'data': None, 'extra': None} when calling https://openapi.alphaess.com/api/getOneDateEnergyBySn?sysSn=ALDXXXXXXXXXX&queryDate=2024-09-02
Server disconnected
Error: Server disconnected when calling https://openapi.alphaess.com/api/getOneDateEnergyBySn?sysSn=ALDXXXXXXXXXX&queryDate=2024-09-02
Unexpected json_response : {'code': 6026, 'msg': 'network is busy', 'expMsg': 'nested exception is org.apache.ibatis.exceptions.PersistenceException: \n### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.\n### The error may exist in class path resource [mapper/td/SysColdataMapper.xml]\n### The error may involve com.alphaess.api.mapper.td.SysColdataMapper.selectOneDayFirstPowerBysn\n### The error occurred while executing a query\n### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.', 'data': None, 'extra': None} when calling https://openapi.alphaess.com/api/getOneDateEnergyBySn?sysSn=ALDXXXXXXXXXX&queryDate=2024-09-02
Unexpected json_response : {'code': 6026, 'msg': 'network is busy', 'expMsg': 'nested exception is org.apache.ibatis.exceptions.PersistenceException: \n### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.\n### The error may exist in class path resource [mapper/td/SysColdataMapper.xml]\n### The error may involve com.alphaess.api.mapper.td.SysColdataMapper.selectEntityList\n### The error occurred while executing a query\n### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.', 'data': None, 'extra': None} when calling https://openapi.alphaess.com/api/getSumDataForCustomer?sysSn=ALDXXXXXXXXXX
```

**Comment by dhi20** [comment]
Rolling back to 5.02 seems to have fixed the issue. I tried 5.03 but it had the same issue.

**Comment by Poshy163** [comment]
Its a `combination` of them giving invalid data (through their server errors here https://github.com/alphaess-developer/alphacloud_open_api/issues/82), and us defaulting to using the value of 0 when receiving invalid data 

They are aware of their server issues, but i can also see if i can work out a solution so instead of 0, it goes into some Unavailable state or something

**Comment by beastien** [comment]
I'm having exactly the same problem as dhi20. Last night it had happened over 60 times.
I've tried using availability templates to make the sensors go unavailable to prevent the spikes, but then other sensors making calculations from those sensors get messed up because they don't receive valid data.

![image](https://github.com/user-attachments/assets/ef0ffa73-f8af-489d-940b-08eb003ab24d)

**Comment by Poshy163** [comment]
Yeah, thats the issue at the moment, if one sensor, lets say solar production "fails" and is defaults to 0, all the other sensors that rely on it get incorrect info, 

One thing we could do is somehow check the values, and if one of them is `None` we could just only return none, which iirc renders the data with the last accessible data-point (to the sensor)? will play around with it today/tomorrow

**Comment by Poshy163** [comment]
The timeouts from the API on their end seems to have stopped in the last 10-20 mins? this shouldn't occur at all anymore

**Comment by cabe1214** [comment]
It may be a little out of scope but any idea how to "clean-up" the wrong values in HA?

**Comment by Poshy163** [comment]
its in the dev tools, in the statistics tab, i have linked the docs for you to check it out

https://www.home-assistant.io/docs/tools/dev-tools/#statistics-tab

**Comment by KortgatGH** [comment]
> The timeouts from the API on their end seems to have stopped in the last 10-20 mins? this shouldn't occur at all anymore

@Poshy163 it seems on my side it still persists - this is for yesterday (2 September):

![image](https://github.com/user-attachments/assets/81c7a039-0c2c-40ce-b8b0-5a6e43fc5076)

**Comment by Poshy163** [comment]
Yeah, we have a solution in the draft PR linked above

**Comment by beastien** [comment]
Happened a couple of times again this afternoon.

![image](https://github.com/user-attachments/assets/087227ae-9876-4fa6-aba0-30ab71b4b42f)

**Comment by beastien** [comment]
And I'm getting this error in the log. 138 times in the last few days.

This error originated from a custom integration.

Logger: alphaess.alphaess
Source: custom_components/alphaess/coordinator.py:54
integration: Alpha ESS (documentation, issues)
First occurred: September 1, 2024 at 11:23:51 PM (138 occurrences)
Last logged: 7:43:32 PM

Unexpected json_response : {'code': 6026, 'msg': 'network is busy', 'expMsg': 'nested exception is org.apache.ibatis.exceptions.PersistenceException: \n### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.\n### The error may exist in class path resource [mapper/td/SysColdataMapper.xml]\n### The error may involve com.alphaess.api.mapper.td.SysColdataMapper.selectOneDayLastPowerBysn\n### The error occurred while executing a query\n### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.', 'data': None, 'extra': None} when calling https://openapi.alphaess.com/api/getOneDateEnergyBySn?sysSn=AL7011022080085&queryDate=2024-09-03
Server disconnected
Error: Server disconnected when calling https://openapi.alphaess.com/api/getLastPowerData?sysSn=AL7011022080085
Unexpected json_response : {'code': 6026, 'msg': 'network is busy', 'expMsg': 'nested exception is org.apache.ibatis.exceptions.PersistenceException: \n### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.\n### The error may exist in class path resource [mapper/td/SysColdataMapper.xml]\n### The error may involve com.alphaess.api.mapper.td.SysColdataMapper.selectEntityList\n### The error occurred while executing a query\n### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.', 'data': None, 'extra': None} when calling https://openapi.alphaess.com/api/getSumDataForCustomer?sysSn=AL7011022080085
Unexpected json_response : {'code': 6026, 'msg': 'network is busy', 'expMsg': 'nested exception is org.apache.ibatis.exceptions.PersistenceException: \n### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.\n### The error may exist in class path resource [mapper/td/SysColdataMapper.xml]\n### The error may involve com.alphaess.api.mapper.td.SysColdataMapper.selectOneDayFirstPowerBysn\n### The error occurred while executing a query\n### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: td_alphacloud_alphaess - Connection is not available, request timed out after 10000ms.', 'data': None, 'extra': None} when calling https://openapi.alphaess.com/api/getOneDateEnergyBySn?sysSn=AL7011022080085&queryDate=2024-09-03

**Comment by Poshy163** [comment]
Yeah, that's what i mean by the server issues. its a problem on their end unfortunately in the docs they just refer to a 6026 as a "internal error", but you can see in the response query its something to do with their database and it taking over 10s 

Tons of people have tried reaching out regarding any fixes, but most of us have just got back lackluster info

**Comment by CharlesGillanders** [comment]
> Tons of people have tried reaching out regarding any fixes, but most of us have just got back lackluster info.

I am coming to the conclusion that "ElevenFan" really doesn't have any autonomy, they are a developer that maintains the code that provides the public API but they don't appear to have any path to accept suggestions for the code nor to provide any support for the actual back end systems that the API is querying.

Their comment to contact after sales support is probably about as much direction as they can provide. We should find out how to correctly raise trouble tickets and then report issues with the API in exactly the same way as we would issues with the actual hardware.

**Comment by beastien** [comment]
Is it possible to make the values not go to zero when this happens as Poshy163 has mentioned?
That's the main issue messing up the graphs and any calculations. If that's possible i think it wouldn't matter so much when these errors happen.
I'm using availability templates at the moment but that still causes miscalculations when the sensors become unavailable.

**Comment by Poshy163** [comment]
Yes there is, in https://github.com/CharlesGillanders/homeassistant-alphaESS/pull/130 it resolves it. im just testing it doesn't break anything else before taking the out of draft,  

You can change the lines of code to fit what ive done, otherwise i plan to allow reviewing sometime in the next few hours, then Charles can bump version + release

**Comment by Gaspode69** [comment]
> Their comment to contact after sales support is probably about as much direction as they can provide. We should find out how to correctly raise trouble tickets and then report issues with the API in exactly the same way as we would issues with the actual hardware.

I guess in this case this was a misunderstanding. ElevenFan fixed the issue in the OpenAPI. The concerned values are delivered again.
