### ISSUE TITLE
Integration failing to setup "unsupported operand type(s) for -: 'str' and 'float'"

### ISSUE THREAD

**Issue by jamiergrs** [CharlesGillanders/homeassistant-alphaESS#129]
The integration suddenly failed to start today and no matter if you reset, delete and re-add I'm still getting the following errors; The integration shows the error as "Failed setup, will retry: unsupported operand type(s) for -: 'str' and 'float'"

Checking the logs the following can be seen
`Unexpected json_response : {'code': 6053, 'msg': 'The maximum number of requests has been reached', 'expMsg': None, 'data': None, 'extra': None} when calling https://openapi.alphaess.com/api/getChargeConfigInfo?sysSn=[removed]`

`Unexpected json_response : {'code': 6053, 'msg': 'The maximum number of requests has been reached', 'expMsg': None, 'data': None, 'extra': None} when calling https://openapi.alphaess.com/api/getDisChargeConfigInfo?sysSn=[removed]`

And addtionally 
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alphaess/coordinator.py", line 84, in _async_update_data
    inverterdata["Solar to Load"] = _pv - _feedin
                                    ~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'float'`

Not sure what's changed but haven't had any issues with the integration or month, app still works fine

**Comment by strickersuk** [comment]
Same for me, I opened issue 128 just before you.

**Comment by Rapt0rx** [comment]
The same issue started this morning on my system.

**Comment by bmannz** [comment]
Yes same issue for me also. Started 1hr ago for me.

**Comment by suds32** [comment]
Same for me as well

**Comment by umrath** [comment]
same

**Comment by strickersuk** [comment]
I close #128 to prevent duplication.

**Comment by ha-es13** [comment]
Same here

**Comment by strickersuk** [comment]
I commented out line 84 in coordinator.py and have most of it back. Hopefully a quick fix for someone much smarter than me.

**Comment by crayner** [comment]
Seeing the same here.

Also in logs: Logger: alphaess.alphaess
Source: custom_components/alphaess/coordinator.py:41
integration: Alpha ESS ([documentation](https://github.com/CharlesGillanders/homeassistant-alphaESS), [issues](https://github.com/CharlesGillanders/homeassistant-alphaESS/issues))
First occurred: 15:22:20 (2 occurrences)
Last logged: 15:22:20

Unexpected json_response : {'code': 6053, 'msg': 'The maximum number of requests has been reached', 'expMsg': None, 'data': None, 'extra': None} when calling https://openapi.alphaess.com/api/getChargeConfigInfo?sysSn=xxxxxxxxxxxxxxxx
Unexpected json_response : {'code': 6053, 'msg': 'The maximum number of requests has been reached', 'expMsg': None, 'data': None, 'extra': None} when calling https://openapi.alphaess.com/api/getDisChargeConfigInfo?sysSn=xxxxxxxxxxxxxxx

Logger: custom_components.alphaess
Source: helpers/update_coordinator.py:354
integration: Alpha ESS ([documentation](https://github.com/CharlesGillanders/homeassistant-alphaESS), [issues](https://github.com/CharlesGillanders/homeassistant-alphaESS/issues))
First occurred: 15:21:11 (34 occurrences)
Last logged: 15:57:41

Unexpected error fetching alphaess data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alphaess/coordinator.py", line 70, in _async_update_data
    inverterdata["Solar to Load"] = await process_value(_pv - _feedin)
                                                        ~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'float'


Hope this helps!  Craig

**Comment by jamiergrs** [comment]
> I commented out line 84 in coordinator.py and have most of it back. Hopefully a quick fix for someone much smarter than me.

This also worked for me, can get all data back except obviously the Grid to Load value

**Comment by Poshy163** [comment]
What da fuckkkkkkk, I'll look into it now

**Comment by TheSimTek** [comment]
Same here. Was fine until o restarted HA

**Comment by Poshy163** [comment]
Ok, an update for yall, seems like for some fucking reason epv is a string?!?!?! No idea why this happened can only imagine it was a mistake?

![image](https://github.com/user-attachments/assets/2bb01ac9-17dc-4c49-8eb5-7fb505528551)

a hot fix solution is to set line 78 of coordinator.py from 

`_pv = await safe_get(_onedateenergy, "epv")` 

to 

`_pv = float(await safe_get(_onedateenergy, "epv"))`

this basically forces the string to be a float

**Comment by techmaved** [comment]
It seems like the api has been fixed. The integration works as usual.

**Comment by Poshy163** [comment]
Yeah, appears to be fixed now, might need a integration refresh to pull the latest API changes 

![image](https://github.com/user-attachments/assets/7ef19320-f52a-413c-a365-8099168fc0c4)

**Comment by DaveBinM** [comment]
Although it’s come back, my total_load sensor is now reporting as 0, which isn't right. Curious if anyone else sees this?

**Comment by jamiergrs** [comment]
> Although it’s come back, my total_load sensor is now reporting as 0, which isn't right. Curious if anyone else sees this?

Mine is also showing as 0 since the integration started failing yesterday

**Comment by Poshy163** [comment]
Huh yeah just noticed that. eload, which we use for the total load, is showing as 0 from the API 😢 
![image](https://github.com/user-attachments/assets/6da8eb09-aa78-4f21-b0d6-1f33e719bfad)

Most of this is our of our control unfortunately, clearly they have messed with the API last night and it has had some side effects...

**Comment by Poshy163** [comment]
it has been mentioned upstream: https://github.com/alphaess-developer/alphacloud_open_api/issues/82
