### ISSUE TITLE
Sensor has no value

### ISSUE THREAD

**Issue by Rasenkardinal** [CharlesGillanders/homeassistant-alphaESS#131]
Hi there,

after the little STRING or FLOAT hiccup with the API I encountered another Problem:
The Sensor-Value for total_load shows always 0. It has worked before.

Any Ideas?

**Comment by Poshy163** [comment]
It a upstream issue (issue with the API). See here: https://github.com/alphaess-developer/alphacloud_open_api/issues/82

**Comment by Rasenkardinal** [comment]
Ahhh,  what a mess.

Thanks for your quick help.

**Comment by Rasenkardinal** [comment]
The sensor data is back again!
