### ISSUE TITLE
Wrong values in the energy dashboard from AlphaESS system

### ISSUE THREAD

**Issue by Meigl89** [CharlesGillanders/homeassistant-alphaESS#132]
Hi everyone, 

hopefully you can help me with this mess, or maybe somebody encountered the same problem. 

Starting from 1st September I'm facing the issue that the energy dashboard shows a complete mess regarding my solar values. 

![image](https://github.com/user-attachments/assets/9994db75-b0ab-465e-9c64-4dc87322dd51)

The reality is this:

![image](https://github.com/user-attachments/assets/1a6d3300-baf7-446a-bbe6-feb500c15c73)

I didn't change anything here for weeks, why should I though, because it was running super smooth. 

Yesterday it was also wrong:

![image](https://github.com/user-attachments/assets/4398b6f4-7d8d-4391-b02c-ddc67c1c2670)

versus reality:

![image](https://github.com/user-attachments/assets/031aaf58-9a6e-4c21-b19b-1f465f5e3e0b)

And for today it will be the same, since its wrong even in the morning hours it shows 4,5kwh of load, in reality its 2,4kwh. 

I honestly dont get it. I thought it came from the battery, because values here are super crazy, but when I remove the battery from the dashboard, the other values are still wrong. 

Funny - or sadly - the entities are completely correct. For yesterday prodcution was 33,3kwh und entitiy says:

![image](https://github.com/user-attachments/assets/e934802a-05ba-433e-8288-e8ba7e124e70)

I'm really struggling in finding the root cause of this.. 

Can anybody give me a hint what may be wrong here?

Thank you all!

**Comment by Poshy163** [comment]
Heya, the issue has been mentioned here: https://github.com/CharlesGillanders/homeassistant-alphaESS/issues/127 and also upstream here https://github.com/alphaess-developer/alphacloud_open_api/issues/82

TL:DR Its a combination of them giving invalid data (through their server errors and long time outs on requests), and us defaulting to using the value of 0 when receiving invalid data. which is causing these spikes, 

A draft PR is open to fix this here: https://github.com/CharlesGillanders/homeassistant-alphaESS/pull/130

**Comment by Meigl89** [comment]
Oh I didn't put that together, that this may be the same problem. Thank you for the information regarding this! 

So I can do nothing but wait, thats fine, now I know that it's not on my end. Hopefully it can be fixed. 

Thank you very much!

**Comment by Euan-p** [comment]
Same problem here. anyone know if the root API problem is being worked on by alphaess or  have we just got the custom PR? Wasn't sure if someone might have found a forum post about the api that i missed.

**Comment by ElevenFan** [comment]
I didn't modify anything in my program，I suggest you find after-sales service to give feedback.
