### ISSUE TITLE
Timestamp Error

### ISSUE THREAD

**Issue by matt-oneill** [CharlesGillanders/homeassistant-alphaESS#147]
The integration stopped working for me a few days ago.

In the logs
![image](https://github.com/user-attachments/assets/27906ccb-4a65-41c4-ae4c-7fad8cc49e82)

I have tried
- Resetting my developer key in open api as this has worked before
- Reloading the integration
- Removing and reinstalling the integration (now I can't add it again)

All successful api calls in postman so I don't think its an issue with the alpha api.

**Comment by Poshy163** [comment]
Is there a chance that your HAOS machine is out of sync of time? only reason you would be receiving that error is when (according to the docs) "the timespan between request timestamp and server timestamp exceeds 300 seconds"

**Comment by matt-oneill** [comment]
I've also tried changing the HA Time Zone to GMT (no daylight saving) in case that caused the incorrect time and then back again to GMT London.
Each time also a fresh install of the integration and rebooting.

Using developer tools the time seems to be 10 minutes out but I can't see any way to set the time manually.
![image](https://github.com/user-attachments/assets/174232d7-f503-4618-8aed-105b0652decd)

10 mins seems an odd offset I would have expected it to be whole hours if its timezone related.

**Comment by CharlesGillanders** [comment]
The timestamp is UTC based - it counts the number of seconds since 1st January, 1970 UTC so time zone is not important.

That your HA is 10 minutes out suggests that its time sync isn't working - are you running HAOS or a VM or something else?  If it's HAOS I am not sure, you may try a complete reboot.  If it's a VM I'd suspect that the underlying OS isn't time synced, you should be able to manually change the time there.

**Comment by matt-oneill** [comment]
HASS OS on raspberry pi 4.
Rebooting the host didn't work and looks to be an ntp issue but can't see any way to change the time manually in HA or OS.

obviously not an issue with the integration so I'll close this and keep looking for solutions with the OS. 
Thanks for your help
