### ISSUE TITLE
alphaess-developer OpenAPI repository gone?

### ISSUE THREAD

**Issue by CharlesGillanders** [CharlesGillanders/homeassistant-alphaESS#150]
Is it just me or has the repo for the open API gone from alphaess-developer?

I went to look up the recent thread on using the API to bind an inverter rather than using the website and I can't find any of that discussion at all any more.

**Comment by Poshy163** [comment]
Im not sure if this relates to elevanfan job being "transferred" or not. He sent me a slack DM a few weeks ago saying: 

"My job has been transferred and I will no longer be responsible for this API. If you have any questions in the future, please contact our after-sales service."

<img width="563" alt="Screenshot 2024-12-01 at 7 30 39 pm" src="https://github.com/user-attachments/assets/ec89aceb-43b8-48f0-84a4-5dcce5a42487">

I have a feeling he was one of the main people who worked on the github and maintained it, and obv with him gone it was for some reason wiped...

**Comment by CharlesGillanders** [comment]
Oh dear.  Well we will see if the API keeps running.  I guess if it develops problems in the long run we could go back to scraping from the unofficial client again.
