### ISSUE TITLE
All sensors showing as unavailable

### ISSUE THREAD

**Issue by utzy79** [CharlesGillanders/homeassistant-alphaESS#151]
For some reason all of my sensors are showing unknown. Was working fine for a couple of years but not now
![image](https://github.com/user-attachments/assets/383198f7-6c3e-4680-b61f-3c7b76d053ef)

**Comment by Poshy163** [comment]
What errors are being displayed are in the logs?

**Comment by utzy79** [comment]
Never mind, was a network issue
