### ISSUE TITLE
Registration on open.alphaess

### ISSUE THREAD

**Issue by rk-code** [CharlesGillanders/homeassistant-alphaESS#153]
Hallo,
I tried to add my inverter also on open.alphaess.com. Unfortunatly I did not get a verification code by email. I just get even after login a internal server error. I have registered my inverter after Installation already at alpha.ess - not open.alpha.ess. Could this interfere? 
Is it also possible to use the API without having registered my inverter at open.alphaess but at alphaess?

Tanks for any support

**Comment by beeare** [comment]
I have exactly  the same issue.

**Comment by Poshy163** [comment]
There used to be an ongoing issue regarding it in the AlphaESS slack/github. And the only solution was to use the API (can bind via the API call) and get the info that way.

I can prolly work on improving the documentation surrounding all of that, now there is seemingly no one at alpha maintaining it

**Comment by CharlesGillanders** [comment]
> There used to be an ongoing issue regarding it in the AlphaESS slack/github. And the only solution was to use the API (can bind via the API call) and get the info that way.
> 
> I can prolly work on improving the documentation surrounding all of that, now there is seemingly no one at alpha maintaining it

I added the API calls for getting the check code and binding the invertor to the postman collection recently so maybe the best way to update the documentation is to refer to using postman to do that registration?

**Comment by Poshy163** [comment]
Yep, I'll update the config flow to include info regarding unable to add an account to openAPI, and link it to the read.md location and update the documentation in relation to that.

I'll open a PR for it later today when I get home

**Comment by rk-code** [comment]
Thank you very much looking forward your update of read.md. 

@CharlesGillanders not clear which postman collection your are refering to... can you comment ?

By the way within the read.md 
"Once registered and logged in follow the instructions from https://github.com/alphaess-developer/alphacloud_open_api to find your inverter SN and CheckCode" looks like is a dead link.

**Comment by Poshy163** [comment]
@rk-code there is a PR open for it now, just pending to be pulled, ive replaced that dead link to the old dev GitHub with a reference to this image here https://imgur.com/a/Xm5t1s0

There doesn't seem to be any other good documentation (and the old link basically showed the same image as i linked)
