### ISSUE TITLE
Intermittent data

### ISSUE THREAD

**Issue by KortgatGH** [CharlesGillanders/homeassistant-alphaESS#17]
![image](https://user-images.githubusercontent.com/49630727/168879596-16fa4b49-6dda-41f4-a720-913beda8ed1c.png)

Anybody else experiencing intermittent Alpha data recently? Mine started playing up around the time that the Alpha web interface was updated, but it was also around the time that HA core-2022.5 was released.

**Comment by Spookster** [comment]
No issues noted here.
A question though - Batt limit? hard coded  or extracted from data elsewhere?

**Comment by KortgatGH** [comment]
Batt Limit is just a local constant so that I can draw a line on the graph.

**Comment by KortgatGH** [comment]
Could my problem be related to this error?

"This error originated from a custom integration.

Logger: custom_components.alphaess
Source: helpers/update_coordinator.py:223
Integration: Alpha ESS (documentation)
First occurred: May 25, 2022, 18:11:26 (31 occurrences)
Last logged: 05:33:20

Error fetching alphaess data:"
