### ISSUE TITLE
Energy coming out of the battery

### ISSUE THREAD

**Issue by davesgraphcore** [CharlesGillanders/homeassistant-alphaESS#18]
Hi,

HomeAssistant wants me to specify the energy coming out of the battery. I can't find this signal. Does it exist?

Thanks!

**Comment by davestubbs** [comment]
Looks like it was removed in 98c470e.

**Comment by CharlesGillanders** [comment]
> Looks like it was removed in [98c470e](https://github.com/CharlesGillanders/homeassistant-alphaESS/commit/98c470e99557e60940d366b9a1f38b4ba3aae80a).

That was a bogus sensor which was removed - the actual sensor for this is the battery discharge one.

**Comment by davestubbs** [comment]
Thanks. My mistake! (I probably shouldn't have just hacked the plugin to test the other one :) )
