### ISSUE TITLE
website change

### ISSUE THREAD

**Issue by Tupsi** [CharlesGillanders/homeassistant-alphaESS#21]
alpha-ess switched to there new domain yesterday, so this plugin fails to pull new data since yesterday.

New domain is https://cloud.alphaess.com/ and should replace the https://www.alphaess.com whereever you use it in the hope this starts working again.

**Comment by CharlesGillanders** [comment]
Thanks, This was reported already https://github.com/CharlesGillanders/homeassistant-alphaESS/issues/20 and I have made the necessary fix.  Details are in that other ticket.
