### ISSUE TITLE
AlphaESS Website Change

### ISSUE THREAD

**Issue by strickersuk** [CharlesGillanders/homeassistant-alphaESS#22]
Alpha ESS have changed from www.alphaess.com to cloud.alphaess.com, this seems to have broken the integration?

**Comment by CharlesGillanders** [comment]
Thanks, This was reported already https://github.com/CharlesGillanders/homeassistant-alphaESS/issues/20 and I have made the necessary fix. Details are in that other ticket.

**Comment by strickersuk** [comment]
Apologies, completely forgot to look at the closed issues!
