### ISSUE TITLE
Advanced Mode required for install - update instructions

### ISSUE THREAD

**Issue by gregpetersau** [CharlesGillanders/homeassistant-alphaESS#25]
Advanced Mode is required to be able to install from integrations
Suggest add to installation instructions

Profile -> Advanced Mode -> On

This is not specific to this integration, but as a step missing in the instructions took me ~45 min to discover.
WIthout advanced mode the Alpha ESS will not show up in Add Integration

**Comment by CharlesGillanders** [comment]
Thank you!  I couldn't figure out why some people where having so much trouble getting this installed.
