### ISSUE TITLE
Stopped Updating

### ISSUE THREAD

**Issue by KortgatGH** [CharlesGillanders/homeassistant-alphaESS#28]
Since this afternoon (27 Aug) my Alpha ESS sensors stopped updating. I tried to uninstall and reinstall the integration, and now I get the following after entering the correct login credentials:
![image](https://user-images.githubusercontent.com/49630727/187034521-205fc87e-e0d8-4532-9f35-9fc310740def.png)
Anybody else experiencing problems?

**Comment by DavidqStokes** [comment]
My AlphaESS is also showing as Unavailable. The AlphaESS app is working fine.

Get Outlook for Android
________________________________
From: KortgatGH ***@***.***>
Sent: Saturday, August 27, 2022 3:26:56 PM
To: CharlesGillanders/homeassistant-alphaESS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CharlesGillanders/homeassistant-alphaESS] Stopped Updating (Issue #28)


Since this afternoon (27 Aug) my Alpha ESS sensors stopped updating. I tried to uninstall and reinstall the integration, and now I get the following after entering the correct login credentials:
[image]<https://user-images.githubusercontent.com/49630727/187034521-205fc87e-e0d8-4532-9f35-9fc310740def.png>
Anybody else experiencing problems?

**Comment by KortgatGH** [comment]
If only we could interface directly to our inverters and not rely on the Alpha server. I wonder if Alpha made a small change that broke the Home Assistant integration without affecting their own mobile and web apps.

**Comment by CharlesGillanders** [comment]
I’m awY this weekend, I’ll take a look at whatever changed as soon as I can.

**Comment by DavidqStokes** [comment]
HA logs show the following:

2022-08-27 15:33:58.273 WARNING (MainThread) [homeassistant.config_entries] Config entry 'name.name@domain.co.uk' for alphaess integration not ready yet; Retrying in background

(Email address changed)

**Comment by Spookster** [comment]
Same issue here, however the values are still being returned by DasLetzteEinhorn's add in:
https://github.com/DasLetzteEinhorn/AlphaESS_Monitor_Hass

So something odd has happened with Charles values and not DasLetzteEinhorn

**Comment by tbgoose** [comment]
@Spookster same for me, Alpha ESS to MQTT add-on by MarioCake still returning values (DasLetzteEinhorn addon).

Thanks for your work @CharlesGillanders, in your own time :)

**Comment by Spookster** [comment]
I use a bit of a failsafe in using both integrations
eg:
`    - name: "Const Solar Battery SOC"
      unit_of_measurement: "%"
      device_class: battery
      state: >
        {%if states('sensor.alxxxxxxxxxxxxxxxx_battery_soc') == 'unavailable' %}
        {{ states('sensor.solar_battery_soc') |int   }}
        {%else%}
        {{ states('sensor.alxxxxxxxxxxxxxxxx_battery_soc') |int   }}
        {%endif%}
`
If both are unavailable, Im screwed :p

**Comment by matt-oneill** [comment]
looks like an issue with the date format
![267E722F-4E2C-4836-83D0-156D84395094](https://user-images.githubusercontent.com/60574293/187062076-d2856cd7-2982-41e7-9bd7-588fd17f656d.jpeg)

**Comment by CharlesGillanders** [comment]
thanks to @matt-oneill I have found the error.  Date format change on the part of AlphaEss.  I'll get a fix built today.

**Comment by KortgatGH** [comment]
Thanks @CharlesGillanders, what would us non-programmer types do without you gurus!?

**Comment by DavidqStokes** [comment]
> Thanks @CharlesGillanders, what would us non-programmer types do without you gurus!?

Seconded!

**Comment by CharlesGillanders** [comment]
I have updated the AlphaEss library to fix the date format issue and I've tried to code it to catch future similar changes.  Time will tell.....

If you are using the HACS method of installing the integration then you will need to go into HACS and update the integration (if HACS hasn't updated the version yet you can force it to be updated using the hamburger menu on the integration in HACS)

If you installed manually you'll need to download the updated integration code from github and restart home assistant,

**Comment by DavidqStokes** [comment]
I have installed the update via HACS (it had appeared) and everything is now working fine. Excellent work Charles and thank you very much for your quick attention to this.

**Comment by KortgatGH** [comment]
Just me or are more people getting "unavailable" responses? Looks like it started around 09:00 UTC today

**Comment by Tupsi** [comment]
hmm, I just "updated" via HACS and now have a broken version because of the changed date. Shouldnt the latest update fix it in any case? I will try to completly delete and reinstall with HACS, maybe that fixes it. Just wanted to let you know that the update process isn't that smooth as hoped.

**Comment by CharlesGillanders** [comment]
@Tupsi - updating to the latest version in HACS will fix the integration but I need to actually write the fix first.  I'll update the open GitHub issue when I have done so.

**Comment by Tupsi** [comment]
and now I remember that you do some stuff with that external lib stuff and that needs an update as well, so I will run and get that by hand installed in the hope it fixes it.

**Comment by Tupsi** [comment]
ok, can someone please clarify if it is currently possible to install a working version or not, because that is still confusing for me to read here, as DavidqStokes above wrote he reinstalled via HACS the latest version and it now works. I have tried that and are now stuck getting my credentials back in (because I removed it completly before the fresh install). If it needs some manuall poking I can do that as I have to issues with going into touch with the command line, just need some pointers where to do/replace what please.

**Comment by Buttercream91** [comment]
@Tupsi - Charles is still working on the Fix, he has not yet released the working update.

**Comment by Tupsi** [comment]
> @Tupsi - Charles is still working on the Fix, he has not yet released the working update.

thanks for the clarification, then I will wait patiently. Is that maybe another/new problem with the dates? Because I remember we already had that a few weeks ago (and fixed). Because as I said, it was running fine here until me stupid pressed update this morning :-)

**Comment by Buttercream91** [comment]
I am not sure, when people started reporting the issue my instance was working fine until I updated to home assistant Core 2022.10.2, and then I got the same error as everyone else.

**Comment by Tupsi** [comment]
yeah, the v10 broke a few things here as well. now it is whining about me having portainer installed and refuses to update. Silly.

**Comment by CharlesGillanders** [comment]
I've just pushed the latest fix which should hopefully prevent future date related API issues....

**Comment by KortgatGH** [comment]
Thanks again for the quick response @CharlesGillanders, you're a star!

**Comment by Tupsi** [comment]
Thank you!
