### ISSUE TITLE
credentials

### ISSUE THREAD

**Issue by StickeyTape** [CharlesGillanders/homeassistant-alphaESS#3]
Hi Charles, 

Sorry - stumbled on your project. and noticed you had your inverters login comitted to the repo. Might want to remove it and redo your repository - and change your login on their website.

I am sure it was unintentional - but dont want someone to break your setup - way to many troublemakers out there.

Cheers mate!

PS: Sorry . issue is prob the wrong place to let you know - but I could not find another way to contact you.

**Comment by CharlesGillanders** [comment]
Thank you, I pulled the file and changed the password at AlphaEss.

I appreciate you letting me know.
