### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by petrzz1** [CharlesGillanders/homeassistant-alphaESS#37]
AlphaCloud V5.0.0.2 
2022-10-16
Add
 Signature verification and anti-crawl data functionality will be added in all APIs of AlphaCloud.

**Comment by gryg427** [comment]
It was probably added maybe 2 hours ago in my case. Access is dismissed by the HACS addon even NodeRed reader :-(. Is there any hope for needed appropriate development?

**Comment by gryg427** [comment]
Repeated log by NodeRed: 

16. 10. 2022 13:52:22[node: Alpha ESS monitoring]
msg : string[163]
"There was an error during login operation into Alpha ESS monitoring portal: SyntaxError: Unexpected end of JSON input↵↵We got the following unprocessable body:↵"

**Comment by matt-oneill** [comment]
Alpha screwing us over again.
Looks like the request now needs to add the following headers
authtimestamp: {epoch unix timestamp}
authsignature: {}
Don't know what the signature is, but usually something like an api key and secret base64 encoded.
I managed to get a response using fiddler to get values for these headers, but when the timestamp and signature don't match this response is returned from AlphaESS
`{
  "code": 9006,
  "info": "Network exception, please try again later!",
  "exMessageInfo": "If you need to use Api, please contact Alpha Sales to purchase authorization"
}`

**Comment by jetscrubber** [comment]
Same issue.....another time! Damn!!

**Comment by KortgatGH** [comment]
The Node-Red Alpha ESS node was updated to attempt to fix this. Maybe there is a clue here in their workaround:
https://github.com/dehsgr/node-red-contrib-alphaess

**Comment by CharlesGillanders** [comment]
Thanks all - I'll be able to look at this tomorrow.

**Comment by CharlesGillanders** [comment]
@matt-oneill proposed changes that fix this for now, thanks Matt.  I've updated the PyPi library and I'll be pushing a version of the homeassistant custom component shortly.  If AlphaESS are determined to prevent 3rd party use of their API this may be a longer term problem.

**Comment by vantech14** [comment]
> @matt-oneill proposed changes that fix this for now, thanks Matt. I've updated the PyPi library and I'll be pushing a version of the homeassistant custom component shortly. If AlphaESS are determined to prevent 3rd party use of their API this may be a longer term problem.

Is there any way there could be a subscription to access their API? Has anyone reached out the Alpha?

**Comment by matt-oneill** [comment]
> > @matt-oneill proposed changes that fix this for now, thanks Matt. I've updated the PyPi library and I'll be pushing a version of the homeassistant custom component shortly. If AlphaESS are determined to prevent 3rd party use of their API this may be a longer term problem.
> 
> Is there any way there could be a subscription to access their API? Has anyone reached out the Alpha?

Yes, here's the response so far
<img width="618" alt="image" src="https://user-images.githubusercontent.com/60574293/196283611-062d4969-145d-4d95-b8ef-35136ef69598.png">

And here's the api response with an invalid signature
<img width="722" alt="image" src="https://user-images.githubusercontent.com/60574293/196283816-3be00610-7d07-4370-bd1f-ce80f94b783c.png">

**Comment by vantech14** [comment]
> > > @matt-oneill proposed changes that fix this for now, thanks Matt. I've updated the PyPi library and I'll be pushing a version of the homeassistant custom component shortly. If AlphaESS are determined to prevent 3rd party use of their API this may be a longer term problem.
> 
> > 
> 
> > Is there any way there could be a subscription to access their API? Has anyone reached out the Alpha?
> 
> 
> 
> Yes, here's the response so far
> 
> <img width="618" alt="image" src="https://user-images.githubusercontent.com/60574293/196283611-062d4969-145d-4d95-b8ef-35136ef69598.png">
> 
> 
> 
> And here's the api response with an invalid signature
> 
> <img width="722" alt="image" src="https://user-images.githubusercontent.com/60574293/196283816-3be00610-7d07-4370-bd1f-ce80f94b783c.png">
> 
> 

Ah Alex is a bundle of joy. I've dealt with him before. I've also reached out. 

Is there perhaps a way to scrape this data from their webpage, rather than using an API that they are obviously keen to block?

**Comment by matt-oneill** [comment]
> > > > @matt-oneill proposed changes that fix this for now, thanks Matt. I've updated the PyPi library and I'll be pushing a version of the homeassistant custom component shortly. If AlphaESS are determined to prevent 3rd party use of their API this may be a longer term problem.
> > 
> > 
> > > 
> > 
> > 
> > > Is there any way there could be a subscription to access their API? Has anyone reached out the Alpha?
> > 
> > 
> > Yes, here's the response so far
> > <img alt="image" width="618" src="https://user-images.githubusercontent.com/60574293/196283611-062d4969-145d-4d95-b8ef-35136ef69598.png">
> > And here's the api response with an invalid signature
> > <img alt="image" width="722" src="https://user-images.githubusercontent.com/60574293/196283816-3be00610-7d07-4370-bd1f-ce80f94b783c.png">
> 
> Ah Alex is a bundle of joy. I've dealt with him before. I've also reached out.
> 
> Is there perhaps a way to scrape this data from their webpage, rather than using an API that they are obviously keen to block?

Hopefully Alex can get us an API key!
I don't think its just the api calls they want to block as the notes mention anti-crawl functionality too.

HA scraper is basic and would need an id or css selector to identify the values, and configuration for each. Scraping values from the website doesn't guarantee any more stability than mimicking the api calls as that can change too.
https://www.home-assistant.io/integrations/scrape/
