### ISSUE TITLE
Solar to Load is not always an increasing measurement

### ISSUE THREAD

**Issue by CharlesGillanders** [CharlesGillanders/homeassistant-alphaESS#4]
@Dry noted:

It may be that different system types report their settings differently. Do you have a Smile B3? I just realised that I can look back at the history of individual sensors and this graphic is the Battery to Load isolated. It was reporting a value when I first installed the component but, oddly, it was a decreasing value. I'm very new to HA so it may be that I don't have this setup correctly.

![image](https://user-images.githubusercontent.com/342807/134766221-41cfb100-edfa-4fd6-87ff-147e0daa3c34.png)

_Originally posted by @dry in https://github.com/CharlesGillanders/homeassistant-alphaESS/issues/1#issuecomment-927092865_

**Comment by Spookster** [comment]
My Solar to load is an increasing value for some reason - it shouldnt be a compounding stat?

I also cant find EHouseLoad as a value, only Eload in reference to Load consumption?

![Untitled](https://user-images.githubusercontent.com/982535/147889136-b332b577-5e94-4a18-8019-928af60edf29.png)
