### ISSUE TITLE
request for Voltage per MPPT

### ISSUE THREAD

**Issue by joitde** [CharlesGillanders/homeassistant-alphaESS#57]
Hi,

@Spookster already implemented the Power of PPV1 and PPV2. I'd like to see the Voltage as well. 
Would it be possible for someone to implement? Or is this something I could achieve myself with configuration?
Little coding experience here...

Best
Hannes

**Comment by Spookster** [comment]
Looking quickly at the docs, the values you are looking for are Upv1 and Upv2
I havent tried to access them, but also using node-red-contrib-alphaess and they arent available from that.

**Comment by joitde** [comment]
oh that was a quick reply. 
Sorry I don't know node-red-contrib-alphaess, what does it do?

**Comment by Spookster** [comment]
I use that component in Node Red alongside Charless code for other reasons:
![image](https://user-images.githubusercontent.com/982535/215878812-47e5653c-8433-4cf0-954b-b862ef473a48.png)

I had a quick look at Upv, tried some code, but it seems its not accessible from the standard json code?
Someone else may be able to confirm
