### ISSUE TITLE
Warning in log after updating to HA 2023.2

### ISSUE THREAD

**Issue by dan-s-github** [CharlesGillanders/homeassistant-alphaESS#61]
After updating Home Assistant to 2023.2 I noticed following warning in the logs

```Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for alphaess using this method at custom_components/alphaess/__init__.py, line 54: hass.config_entries.async_setup_platforms(entry, PLATFORMS)```

![Capto_Annotation](https://user-images.githubusercontent.com/20974454/216482989-8c229b0b-0d02-48c8-9e08-b9d4ca9fae46.png)

**Comment by CharlesGillanders** [comment]
Thank you for spotting this.

I'm looking at the documentation and I see the new requirements are covered here https://developers.home-assistant.io/docs/config_entries_index#for-platforms

I will need to make adjustments to this integration to comply with the updated standard.

**Comment by CharlesGillanders** [comment]
Fixed in release https://github.com/CharlesGillanders/homeassistant-alphaESS/releases/tag/v0.3.3

**Comment by dan-s-github** [comment]
Sorry for late reply, only had remote access to system and didn't want to do updates when not at home.
I can confirm that the above warning has disappeared.
Thanks for making this integration and keeping it up to date
