### ISSUE TITLE
No data fron https://cloud.alphaess.com/

### ISSUE THREAD

**Issue by ckarrie** [CharlesGillanders/homeassistant-alphaESS#62]
![image](https://user-images.githubusercontent.com/4140156/216536417-9990a380-1d81-4a12-8770-e4570e0355cb.png)

I get no statistics, only realtime.

I know this is ~~probably~~ not an integration error, but can somebody confirm this or is it just me?

**Comment by CharlesGillanders** [comment]
I'm certainly seeing my own statistics correctly.  The image you attached was from the AlphaCloud service.  Is that showing statistics for today or not?  If AlphaCloud doesn't have statistics then this integration will not either - I can only pull what is available on Alpha.

**Comment by ckarrie** [comment]
Yes, the screenshot is from today.
Okay thank you, then maybe the time settings of my Alpha are incorrect. 

Yesterday statistics ends at 22:30.

![image](https://user-images.githubusercontent.com/4140156/216575795-ae7607fb-d565-4a2d-86d7-4fb878ce227c.png)

**Comment by ckarrie** [comment]
Yeah, its definately a time offset. Marked as fixed
