### ISSUE TITLE
Sensor to indicate status of grid charging/discharging

### ISSUE THREAD

**Issue by milkmanrox** [CharlesGillanders/homeassistant-alphaESS#68]
I've been using the service to enable grid charging for my system at certain times, but would also like to query the status as a condition during an automation.

Is this something you could add?

**Comment by Spookster** [comment]
Pretty sure the code by mat at the moment is only able to set the mode and we cant query the status.

If that is the case, then perhaps look at using a helper in HA to maintain the last state (include it in any script / automation)
