### ISSUE TITLE
Incorrect Power Usage Readings

### ISSUE THREAD

**Issue by DaveBinM** [CharlesGillanders/homeassistant-alphaESS#73]
I'm not entirely sure if this is an AlphaESS issue or a HA issue, but I couldn't see anything obvious in their issues related to this.

Sometimes I see my power usage is duplicated at some stage of the day, sometimes at the end of the day, and other times in the middle of the day, where it adds together all the energy usage from the day so far, and puts it as a single hour as shown below. Happy to file with HA if this is a HA issue, but wanted to check here first, in case other AlphaESS users have seen this

<img width="1638" alt="image" src="https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/19317607/c17f513b-02c5-403b-ab68-fcf5dd5574e1">

<img width="1619" alt="image" src="https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/19317607/749ca900-f5a0-4090-9eef-80dcc2711f6e">

**Comment by zaphod0** [comment]
Hi, I am having the same issue and came across your post. Upon looking into it further, I can see that the solar production entity in HA gets reset to 0 and immediately back to its original value within the same hour where HA Energy shows the spike in production / usage. 

Not sure what might be causing this or of it is an issue with the Integration or HA.  

![Screenshot 2023-06-02 at 20 46 21](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/26097743/60270c88-ab47-463e-b704-14efed61fff5)
![Screenshot 2023-06-02 at 20 46 54](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/26097743/ff3d7bb7-9e49-475b-8613-81b061fb6fb4)

**Comment by beastien** [comment]
I didn't see this post, but I believe it's the same problem.
https://github.com/CharlesGillanders/homeassistant-alphaESS/issues/74
