### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by ahmedhoumeci** [CharlesGillanders/homeassistant-alphaESS#77]
Hi there.
I've an issue with the AlphaEss integration.
Until friday, everything works well.
Now when I try to re-configure the integration I have the following error when I write my credentials: Unknown error occured

So, I cannot use the integration.
Any suggestion?

Thanks

**Comment by ahmedhoumeci** [comment]
I found the new pre-release for the workaround. How can I use it?

**Comment by CharlesGillanders** [comment]
See issue 76 https://github.com/CharlesGillanders/homeassistant-alphaESS/issues/76
