### ISSUE TITLE
Add integration broken

### ISSUE THREAD

**Issue by Weltschmerz-dev** [CharlesGillanders/homeassistant-alphaESS#81]
![image](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/59337424/d9c8b46e-cba8-4dae-a581-071b05f943f8)

**Comment by Weltschmerz-dev** [comment]
Also when i try to enter email and passw regardless i get unknown error, when inspecting this call in the browser all i can see is:

500 Internal Server Error

Server got itself in trouble

**Comment by Weltschmerz-dev** [comment]
Just read the other issue, i will register an alphacloud account now, may still want to fix the boxes being empty tho and maybe put a disclaimer :)

**Comment by CharlesGillanders** [comment]
Fixed the issue with the missing text.
