### ISSUE TITLE
No Data since 2 days

### ISSUE THREAD

**Issue by demsarinic** [CharlesGillanders/homeassistant-alphaESS#83]
Hello,

since two days no data will receive in HomeAssistant. Problem with alpha-cloud?

![image](https://github.com/CharlesGillanders/homeassistant-alphaESS/assets/93226293/839413ea-d3a5-4cce-a950-a18bacbef95b)

Thanks!

**Comment by CharlesGillanders** [comment]
AlphaESS is requiring all integrations to switch to using their official API - it has a totally different authentication mechanism.  Please make sure to follow the OpenAPI instructions on the github page [https://github.com/CharlesGillanders/homeassistant-alphaESS](https://github.com/CharlesGillanders/homeassistant-alphaESS)
