### ISSUE TITLE
Feature Request:  Forced Export To GRID

### ISSUE THREAD

**Issue by nraimo1** [CharlesGillanders/homeassistant-alphaESS#88]
It seems this is possible with alpha ess for LOOP and other providers around the world its also possible if using the modbus is there a way to access this feature via the API and push the battery into exporting to the grid?

**Comment by CharlesGillanders** [comment]
The integration I'm using is not based on modbus so I cannot comment about that.  As for the official AlphaESS open API (which I am using) the AlphaESS team have stated that forced export to the grid is NOT a feature that the open api will support and that forced export as a feature is only available in a commercial api  suitable for power generation companies.

Here's a short thread on the topic.

https://github.com/alphaess-developer/alphacloud_open_api/issues/43
