### ISSUE TITLE
alphaess.setbatterycharge stopped working

### ISSUE THREAD

**Issue by haardman** [CharlesGillanders/homeassistant-alphaESS#96]
I'm not sure when or why but my alphaess.setbatterycharge is no longer working.

If I test it using developer Tools I get a green tick but the settings don't change on the Alpha settings.
The alphaess.setbatterydischarge works fine.
I'm on 0.4.7

I'm not savvy enough to figure out which part of the system is not working.  Any ideas?

Core 2023.12.4
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2

**Comment by CharlesGillanders** [comment]
Alpha introduced a rate limit of setting battery charge/discharge only once every 24 hours.  There are threads on their support forum requesting allowing slightly more frequent configuration but so far no change.
