### ISSUE TITLE
"Alpha ESS: Set Battery Charge" service not working

### ISSUE THREAD

**Issue by braindeadmalc** [CharlesGillanders/homeassistant-alphaESS#98]
The service "Alpha ESS: Set Battery Charge" appears to run OK but does not set the Charge settings on the Alpha B3
This was working last time I used it 
All entities can be read fine which implies the API user validation is still OK but then it should be, I've not changed it.

**Comment by Poshy163** [comment]
This is due to a change upstream, not due to the API. It is now set to one change every 24 hours.

See here [Interface restriction announcement
](https://github.com/alphaess-developer/alphacloud_open_api/issues/54)

**Comment by braindeadmalc** [comment]
> This is due to a change upstream, not due to the API. It is now set to one change every 24 hours.
> 
> See here [Interface restriction announcement ](https://github.com/alphaess-developer/alphacloud_open_api/issues/54)

Thanks for this. It's a seriously good reason not to buy Alpha.
Really not impressed.

**Comment by Poshy163** [comment]
I guess they just had to draw a line between faults to convince.

They store that information in flash memory that degrades rapidly when changing data often. And I don't they ever thought that people would be changing it quite so regularly.

**Comment by braindeadmalc** [comment]
I guess this Issue could be closed now?

**Comment by Poshy163** [comment]
I agree. 

Cc/ @CharlesGillanders

**Comment by haardman** [comment]
Alpha have stated that changes are now limited to once every 10 seconds and yet I still don't seem to be able to make any changes from HA.  Do I need to do anything
